[package]
name = "kartoffels-toolbox"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
ciborium = { workspace = true }
clap = { workspace = true }
kartoffels = { path = "../kartoffels" }
serde = { workspace = true }
serde_json = { workspace = true }
