[workspace]
resolver = "2"

members = [
    "crates/hellbots",
    "crates/hellbots-pac",
    "crates/hellbots-roberto",
    "crates/hellbots-server",
    "crates/hellbots-vm",
    "crates/hellbots-vm-tests",
]

[workspace.dependencies]
anyhow = "1.0.82"
axum = { version = "0.7.5", features = ["macros", "ws"] }
ciborium = "0.2.2"
clap = { version = "4.5.4", features = ["derive"] }
derivative = "2.2.0"
elf = "0.7.4"
futures-util = "0.3.30"
glam = { version = "0.27.0", features = ["serde"] }
indoc = "2.0.5"
itertools = "0.12.1"
maybe-owned = { version = "0.3.4", features = ["serde"] }
pretty_assertions = "1.4.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
serde = { version = "1.0.200", features = ["derive"] }
serde_bytes = "0.11.14"
serde_json = "1.0.117"
spin = "0.9.8"
talc = "4.4.1"
test-case = "3.3.1"
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features = ["cors", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
