[package]
name = "kartoffels-cpu"
version.workspace = true
edition.workspace = true

[dependencies]
object.workspace = true
serde.workspace = true
serde_bytes.workspace = true
thiserror.workspace = true

[dev-dependencies]
itertools.workspace = true

[lints]
workspace = true
