[package]
name = "kartoffels-ui"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
futures-util.workspace = true
glam.workspace = true
ratatui.workspace = true
termwiz.workspace = true
tokio.workspace = true
tracing.workspace = true
