[alias]
build-roberto = "build -p kartoffels-roberto --release --target misc/riscv64-unknown-bot.json -Z build-std -Z build-std-features=compiler-builtins-mem"
build-vm-tests = "build -p kartoffels-vm-tests --release --target ../../misc/riscv64-unknown-bot.json -Z build-std -Z build-std-features=compiler-builtins-mem"

[target.riscv64-unknown-bot]
rustflags = [
    "-C", "link-arg=-Tmisc/riscv64-unknown-bot.ld",
]
