[alias]
build-cpu-tests = "build -p kartoffels-cpu-tests --release --target ../../riscv64-kartoffel-bot.json --target-dir ../../target.riscv -Z build-std=alloc,core -Z build-std-features=compiler-builtins-mem"

[target.riscv64-kartoffel-bot]
rustflags = [
    "-C", "link-arg=-Triscv64-kartoffel-bot.ld",
]
