[package]
name = "kartoffels-store"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
kartoffels-utils = { path = "../kartoffels-utils" }
kartoffels-world = { path = "../kartoffels-world" }
tokio.workspace = true
tracing.workspace = true
