[package]
name = "kartoffels"
version.workspace = true
edition.workspace = true
default-run = "kartoffels"

[dependencies]
kartoffels-server = { path = "../kartoffels-server" }
kartoffels-toolbox = { path = "../kartoffels-toolbox" }

anyhow.workspace = true
clap.workspace = true
